version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: scheduly
      POSTGRES_PASSWORD: 12345!!
      POSTGRES_DB: scheduly_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: